
POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
  "title": "Another blog",
  "author": "Ross",
  "url": "www.google.com",
  "likes": 3,
  "userId": "61f9c39539c0478dabd5613d"
}